### ISSUE TITLE
Add Python support

### ISSUE THREAD

**Issue by mikesamuel** [google/closure-templates#1]
Migrated from https://code.google.com/p/closure-templates/issues/detail?id=1

---

Reported by dinoboff, Nov 8, 2009
It would be great to be able to compile Soy templates to Python.

Project Member  #1 kai.huang
Sorry, there are no current plans to add Python support.
Status: WontFix 
Labels: ­Type­Defect Type­Enhancement 
#2 dolapo

would you take outside contributions for this?

Project Member  #3 kai.huang
If you were to actually write a high quality backend implementation of Soy for Python, 
with support for all the current features, then I'm sure we would be happy to add it to 
the project. The main problem would be that going forward, we wouldn't have the 
resources to maintain it when we add new features to the other backends, and it may even 
break if we make certain large changes (probably not often though). But if you're 
willing to maintain the Python backend when it gets broken or to implement key new 
features, I'd say go for it!
PS. I'm going to be on leave for most of Q3, so it would be Q4 before it can be added to 
the main project.
PPS. I think I recognize you as a Xoogler? Is that right?
#4 mark@testing­software.org

This is confusing to me. I could not find a Soy for Python. Is it that I looked at the 
wrong places? Is dolapo or somebody else still working on a port?
Is there some research / dialog available on the benefits of having server side 
templates in an Ajax application. I think mainly the data exchange will be XHR but I can 
think of cases where a server side template could be helpful like creation of the 
initial html page.
#5 kai@google.com

I think there are some 3rd party Python implementations of Soy. Obviously, I can't vouch 
for their accuracy in behavior and features.
I'll also keep an eye out for engineers inside Google who want to add a Python backend 
to Soy.
#6 lalinsky

The issue is closed now, but just FYI, I'm working on adding Python backend at 
https://bitbucket.org/lalinsky/closure-templates/overview
Should I submit a patch when I'm done? Would an external contribution be accepted?
#7 lalinsky

https://oxygene.sk/2014/03/closure-templates-soy-for-python/
#8 gboyer@google.com

Wow, awesome! Thanks for this! This is actually something someone else was looking at 
internally... I didn't catch a glimpse of this until now. I'm going to touch base with 
the engineer who has been working on this.
One very unfortunate thing is that we been far too lazy in updating the open source 
version of Soy, so it's likely there will be a large version gap; in the next version we 
have much better support for strict autoescaping, for example. Once we get our open 
source version up to date (I can't guarantee when that will be unfortunately) we can see 
whether it is still convenient to patch, or whether the person working on it internally 
is close enough to something workable that it makes sense just to finish that.
Thanks again! This is amazing!

**Comment by Ubehebe** [comment]
This is underway. See e893159f0c4e187080c28268fb28c67bbba84fd6 and 999749c4d9748eee8caa7eba57783734d1c03a49.

**Comment by DavidCPhillips** [comment]
Hey Folks,

I'm sorry for not providing public info on the state of Python earlier. So here's some background and a quick state of the union.

Late in 2013 the topic of using Soy templates with a Python backend came up internally and we began some early prototyping. The work went pretty quickly at first, getting a mostly complete prototype implementation ready early in the year. However, much of that code was in a pretty ugly state, including much duplication with the JS implementation. Unfortunately, before we could clean it up, the work basically stopped due to various other priorities (Shameless plug for http://youtube.github.io/spfjs/).

Anyway, back to present tense, we've got some time again and are in the process of slicing off manageable chunks from the prototype, cleaning them up, and getting them reviewed/submitted. Currently submitted code includes the Python runtime libraries, and the basic compiler structure and file creation, with more reviews ongoing.

We're aiming to get the rest of the implementation into the main codebase by the end the of Q1.

The other point I should note is that at this point we've made a decision to only start with support for Soy V2.2 in Strict mode.

**Comment by hitsthings** [comment]
Just want to say - I'm super happy you're working on this. It would be awesome to have for us since it means we can share templates between our JVM products and Python ones. Thanks!

**Comment by hitsthings** [comment]
On further thought. Is there a reason you're not basing your work off the version by lalinsky? It seems outdated now, but fairly complete. Are you unhappy with the quality, or are there legal concerns, or something else getting in the way?

Cheers!

**Comment by viridia** [comment]
There's a simple answer, which is that for both technical and policy
reasons we were not able to accept 3rd party contributions until recently,
and by that time the Python backend work had already been underway
for quite a while.

On Thu, Feb 12, 2015 at 4:15 PM, hitsthings <notifications@github.com>
wrote:

> On further thought. Is there a reason you're not basing your work off the
> version by lalinsky? It seems outdated now, but fairly complete. Are you
> unhappy with the quality, or are there legal concerns, or something else
> getting in the way?
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/closure-templates/issues/1#issuecomment-74181502>
> .
>



-- 
-- Talin

**Comment by hitsthings** [comment]
Thanks @viridia ! Good to know.

**Comment by hitsthings** [comment]
Hi all!

Just wanted to check up on this since @DavidCPhillips noted that "We're aiming to get the rest of the implementation into the main codebase by the end the of Q1."

I see you guys did some work up until last month at least - https://github.com/google/closure-templates/tree/master/java/src/com/google/template/soy/pysrc

Is it done (does that stuff work / is it supported?) Is it taking longer than expected? Is it on the backburner again? Are there things the community can do to help out with it?

Thanks so much for all you're doing!

**Comment by DavidCPhillips** [comment]
Hello again @hitsthings.

As you saw, we actually finished up the core compiler/runtime implementation about a month a go! It's currently passing all of our internal integration tests, and has non-deprecated feature parity with the other compilers.

The only reason I haven't closed this bug, and made a more general announcement, is that we'd like to get some projects up and running to work out the kinks. There are a couple small efforts underway that I'm sure will reveal some warts as we get into more complex templating.

So, with that said, the most helpful thing the community could do, would be to try it out as an early adopter. If you have a codebase you'd like to transition, please give it a shot and file bugs for any strange behavior.


Compilation notes:
Python Target: java/src/com/google/template/soy/SoyToPySrcCompiler.java
Most of the flags are identical to the other compilers, with a few additions. Primarily the runtimePath which is a required flag.

**Comment by hitsthings** [comment]
Love it, that's great to hear! I'll set it up with our internal tools and see how we go. Thanks a ton!
