### ISSUE TITLE
literal tag and comments not working together nicely with toSourceString

### ISSUE THREAD

**Issue by StefanLiebenberg** [google/closure-templates#102]
We do some pre-processing of our templates, which involves running visitors on the SoyFileSetRootNode, modifying the tree and printing it all back to soy files with `.toSourceString`

When there is a `/** */` comment inside the `{literal}` a literal tag, its not preserved well in this paradigm.

For example, the following template:

```soy
/**
 *
 */
{template .Bug kind="text"}
  {literal}
    /** @type {my.Factory} */
   var factory = new my.Factory()
  }});
  {/literal}
{/template}
```

Will become this after `toSourceString`

```soy
/**
 *
 */
{template .Bug kind="text"}
{\n}    /** @type {lb}my.Factory{rb} */{\n}   var factory = new my.Factory(){\n}  {rb}{rb});{\n} {sp}
{/template}
```

Now the `/** */` comment is not inside a {literal} anymore and will be removed when the template is called.

**Comment by mikesamuel** [comment]
Pulled internally and will be included in the next release.

**Comment by lukesandberg** [comment]
@StefanLiebenberg 

could you let us know what kind of preprocessing you are doing?  toSourceString isn't a well supported api (we mostly just use it for debugging internally), so there might be some other, better api we can point you towards

**Comment by StefanLiebenberg** [comment]
We have two usages for this at the moment,

Our build flow is as follows, we do pre-processing of the soy ast, and we print it out to new soy files. The new soy files are compiled to JavaScript and also copied into a zip container. The zip container is uploaded to our service which unpacks, compiles and serves the new soy files.

The first use case for this to support conflicting deltemplates with prioritised delpackages, we take a prioritized List<String> of delpackages and remove any conflicting deltemplates by giving preference to the first delpackages in the list. This way we can create complex delpackages with many template overrides without having to care about conflicts. 

Then, the second use case, we have some plugin functions that we only care about at build time. We analyse them to gather information for other steps in our build process and replace them with placeholder text references. We have to remove these functions from the soy before it is sent to our server or compiled to JavaScript, here we just replace the relevant AST nodes for these functions with predefined results instead. 

`toSourceString` is a crucial for us, as we want to sent already processed soy files to the server and we don't want to send the processor code with it. It would also help a bit if the AST was more accessible on the SoyFileSet class.

Hope this made some sense.

**Comment by lukesandberg** [comment]
For the second case (plugin functions), it should be possible to do everything you need via the normal plugin mechanism.  You can implement a SoyJsSrcFunction that just calculates the result inline. 

For the first case, you could potentially handle this entirely outside of the ast by changing the way you issue your compilation commands (just don't include the delpackages you don't want).  

The reason the AST isn't that accessible is completely intentional, it isn't a public API, in fact most of it comes with this comment attached https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/soytree/SoyNode.java#L36
Internally, we have discussed deleting toSourceString in the past and we typically only use it for debugging purposes, not as an AST transformation tool.
