### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by pcj** [google/closure-templates#171]
There seem to be quite a few differences between master and the latest release from 2018-03-14.  Can someone cut a new release?

**Comment by iteriani** [comment]
I am currently moving out all the development we've done in google3, but it's quite a lot of stuff. Hold on tight :)

**Comment by iteriani** [comment]
I think I pushed the compiler to maven (this is my first time). Let me know if it hasn't happened.

**Comment by teppeis** [comment]
@iteriani It isn't available in maven repo.
https://repo1.maven.org/maven2/com/google/template/soy/

**Comment by iteriani** [comment]
OK it should be there now.

**Comment by teppeis** [comment]
@iteriani Thank you! But 2019-03-07 and 2019-03-08 were removed...

**Comment by iteriani** [comment]
My apologies :( I'm not at all familiar with Maven. Is that an issue? They are mostly the same binary

**Comment by teppeis** [comment]
@iteriani `2019-03-07` is important for me, because a big change "Disallow doc-comment @param declaration."  (https://github.com/google/closure-templates/commit/83bae36bdd341df04a3955daf4437744b7ee5f41) happens after that.
I don't know other people want it, but I'm happy if I could get it from maven.

**Comment by iteriani** [comment]
Let me try this.

**Comment by iteriani** [comment]
OK 03/07/2019 is on maven.

**Comment by teppeis** [comment]
thank you!!!
