### ISSUE TITLE
"Unknown" Type parameter results in failed type checks

### ISSUE THREAD

**Issue by robfig** [google/closure-templates#218]
I'm attempting to upgrade our usage of closure templates from 2017-08-08 to 2020-08-24, and I wanted to ask about parameter types. We currently have widespread usage of soydoc params, and I've automatically migrated them to header params with an unknown type, like `{@param NAME: ?}`. 

I'm seeing errors like the following:

```
/Users/robfig/alpha/src/com/corp/admin2/app/views/Categories2/category.soy:95: error: Type mismatch on param category: expected: ?, actual: map<string,?>
95:             {param category: map(
                ~~~~~~~~~~~~~~~~~~~~~~
96:               'id': $categoryParentId
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
97:             ) /}
    ~~~~~~~~~~~~~~~~
```

The template it's calling has that parameter defined as type `?`:
```
{template .single}
{@param? category: ?} // The category currently set
{@param? placeholder: ?} // Placeholder text for the search input
```

The above error is complaining that I'm passing an argument whose type it knows to a template with that parameter defined as an unknown type `?`. 

I don't believe an error should be reported. Is this a bug in the type-checking system, or have I misunderstood the documentation?

Thank you

**Comment by emspishak** [comment]
A few of Soy's newer types (like maps, which replace the legacy_object_map type) purposefully don't interop with the unknown type. For maps, there are technical reasons for this, but we also want to encourage people to use types instead of the unknown type.

For maps specifically, they can't be passed to an unknown-typed parameter (this is what you're seeing) and an object of the unknown type can't be passed as a map-typed parameter. Essentially, maps can't be converted to or from unknown-typed objects.

In this case, the fix is to switch the type of the parameter from `?` to `map<string, ...>`.

Hopefully this helps!

**Comment by robfig** [comment]
Ah, if I migrate our legacy map literals to use `legacy_object_map` or `record` instead of map, it works out. This is no problem. Thanks for the insight!
