### ISSUE TITLE
Support compatible deltemplates with different optional arguments

### ISSUE THREAD

**Issue by nicks** [google/closure-templates#33]
Right now, if you have two deltemplates that accept different optional arguments, you get an error. Here's an example.

```
/**
  * @param? nickelCount
  */
{deltemplate coin.item variant="'nickel'"}
  I have {$nickelCount} nickels
{/deltemplate}

/**
  * @param? dimeCount
  */
{deltemplate coin.item variant="'dime'"}
  {if $dimeCount > 100}I'm rich{/if}
{/deltemplate}
```

closure-templates complains "SoySyntaxException: Found delegate template with same name blahblah but different param declarations"

I don't understand why this is a syntax error. The declarations are perfectly compatible with each other. Is there a good reason why I have to list the optional params of all the other deltemplates?

**Comment by leo-guinan** [comment]
It seems to me that a more logical way to write this would be to have a count that both templates would use. In the "dime" variant, the count is of dimes, whereas the "nickel" variant count would refer to nickels. I believe it is not allowed like that, since we don't know at compile time which delegate we would use, so any delegate would need to support all possible parameters.

**Comment by nicks** [comment]
it's a toy example, don't be silly.

all delegates do support all possible parameters. they just ignore some of those parameters. I shouldn't have to declare that I'm ignoring a parameter.

**Comment by leo-guinan** [comment]
Of course it is a toy example, but it does not demonstrate any reason to desire that behavior. These templates are very strict about requiring parameters, and using the required parameters. It blows up at compile time if the required parameter is not there. If you have several options for templates to choose, how can soy decide whether or not the specific parameter is required? In my eyes, it is a bit like overloading methods in Java. In order to overload, it is necessary to match signatures exactly.

**Comment by nicks** [comment]
"It blows up at compile time if the required parameter is not there." - Just for the record, this is simply not true for deltemplates.

_shrug_, if the team feels that this warning adds value, that's fine. We've already forked our version of closure-templates to remove this warning.

**Comment by leo-guinan** [comment]
Correct, sorry I did not explain my thinking very well on that. My point was that given the strictness of the regular template, keeping in line with that with the deltemplate makes sense.

Now, given that your team feels the warnings are extraneous, and have already disabled them, this starts to make sense. Perhaps it would be beneficial to define a strict mode, in which all of these are enforced, whereas if disabled, it wouldn't try to enforce all these rules. Thanks for that clarification.

**Comment by Ubehebe** [comment]
@nicks This seems like a pretty reasonable change, and it seems unlikely to cause much (any?) breakage in our existing templates. Can you send a PR? (Looks like it's been a while since you merged Medium's fork.)

**Comment by nicks** [comment]
sure, i'll try to put a PR together soon.
