### ISSUE TITLE
Setting `autoescape` on a template causes the template to silently fail.

### ISSUE THREAD

**Issue by ChrisNeveu** [google/closure-templates#44]
We have several templates with an `autoescape` value set. Including any of these templates in a `SoyFileSet` causes all templates to fail with `com.google.template.soy.tofu.SoyTofuException: Attempting to render undefined template`.

An example:
```
// foo.soy
{namespace foo}

/**
 * Template with contextual autoescape.
 */
{template .manualAutoEscape autoescape="false"}
	Manual AutoEscape
{/template}
```
```
// bar.soy
{namespace bar}

/**
 * Hello World
 */
{template .helloWorld}
	Hello World
{/template}
```
```scala
// test.scala
val testFiles = SoyFileSet.builder
   .add(new URL("file:foo.soy"))
   .add(new URL("file:bar.soy"))
   .build
   .compileToTofu

   println(testFiles.newRenderer("foo.manualAutoEscape").render)
   println(testFiles.newRenderer("bar.helloWorld").render)
```
Both templates fail with `Attempting to render undefined template`. Removing the `autoescape="false"` from `.manualAutoEscape` causes both to succeed.

**Comment by ChrisNeveu** [comment]
I should add, the version we are using is `"com.google.template" % "soy" % "2015-04-10"`

**Comment by johnsensible** [comment]
Just to say we're seeing this behaviour too.

We're trying to upgrade to the latest version (2015-04-10) and as we've previously been using noAutoescape in a couple of places wanted to be able to set the autoescaping to the old behaviour (i.e. contextual).  Setting autoescape on either the individual template or namespace doesn't seem to work.

**Comment by lukesandberg** [comment]
I believe that you now need to set it to "deprecated-contextual",

**Comment by johnsensible** [comment]
Ah that worked!

Digging in I see those values seem to be defined here:

https://github.com/google/closure-templates/blob/e049b2e673a5a9571aaa088f4c6d2d434d444d7b/java/src/com/google/template/soy/soytree/AutoescapeMode.java

So the valid values for autoescape would seem to be:

* deprecated-noautoescape
* deprecated-noncontextual
* deprecated-contextual
* strict

So I guess the main bug really is not getting an error when autoescape doesn't match one of those valeus.  That and the documentation not matching.  It still references true/false/contextual in these locations:

* https://developers.google.com/closure/templates/docs/commands#namespace
* https://developers.google.com/closure/templates/docs/commands#template
* https://developers.google.com/closure/templates/docs/security#contextual

Just mentioning this here, as someone else might find it useful.

I don't seem to see the docs in the Repo here - otherwise I'd ask if you want them updated...

Anyway, thanks again for the info.  Saved quite a bid of head scratching...

cheers,

John

**Comment by lukesandberg** [comment]
I think I may have fixed the poor error message issue in
https://github.com/google/closure-templates/commit/19c61de601b6ca862401c7f3e2405c563a04ffa7

I think you are just on an earlier release (sorry!).

Thanks for the pointer about the docs, I'll try to get those fixed

**Comment by johnsensible** [comment]
OK, glad to hear it's fixed and you're on top of the docs.

Guess they'll be a new release soonish?

**Comment by lukesandberg** [comment]
@Ubehebe is in charge of maven/github pushes

**Comment by lukesandberg** [comment]
re docs, it looks like there is an effort underway to convert all our existing docs to markdown and (eventually) get them into this repository.  so updating the docs may take a while :(

**Comment by lukesandberg** [comment]
....two months later the docs are updated.  Sorry, I just lost track of this.

**Comment by johnsensible** [comment]
Hey it's done at least!  Thank you.
