### ISSUE TITLE
map get values doesn't work?

### ISSUE THREAD

**Issue by matiwinnetou** [google/closure-templates#64]
```
    {let $formattableDays: [
      'MONDAY':    'Monday',
      'TUESDAY':   'Tuesday',
      'WEDNESDAY': 'Wednesday',
      'THURSDAY':  'Thursday',
      'FRIDAY':    'Friday',
      'SATURDAY':  'Saturday',
      'SUNDAY':    'Sunday'
    ]/}

    {$formattableDays['MONDAY']} 
```

results in an error:

com.google.template.soy.base.SoySyntaxException: In file /Users/mszczap/Devel/mobile/public-search-germany-webapp/build/classes/main/soy/pubse/includes/configJs.soy:55:9, template pubse.includes.configJs: Invalid expression "$formattableDays['MONDAY']": Type [FRIDAY: string, MONDAY: string, SATURDAY: string, SUNDAY: string, THURSDAY: string, TUESDAY: string, WEDNESDAY: string] does not support bracket-access.

Why? How to fix this?

We are using version 

<dependency>
    <groupId>com.google.template</groupId>
    <artifactId>soy</artifactId>
    <version>2015-04-10</version>
</dependency>

**Comment by matiwinnetou** [comment]
ok, I found this hack:

{let $m: quoteKeysIfJs(['a': 1, 'b': 'blah'] /}

{$m['a']}

but I don't think this is nice, is it possible to support this in an easier way?

**Comment by lukesandberg** [comment]
it would work if you did $formattedDays.MONDAY :(

the issue is if you define a map-literal with string constant keys we infer
it to be a 'record' definition.  This is problematic as you have
discovered.  Another workaround is to make one of your keys in the record
not a constant

e.g.

{let $formattableDays: [
      'MONDAY' + '':    'Monday',
      'TUESDAY':   'Tuesday',
      'WEDNESDAY': 'Wednesday',
      'THURSDAY':  'Thursday',
      'FRIDAY':    'Friday',
      'SATURDAY':  'Saturday',
      'SUNDAY':    'Sunday'
    ]/}

would 'fix' it too.

The problem is that we don't have a good syntax to distinguish 'record
literals' from 'map literals' and instead we use a heuristic of "are all
the keys constant strings?" which isn't ideal.

maybe we should introduce some kind of explicit constructor for maps?

**Comment by matiwinnetou** [comment]
I like the idea of special constructor for maps the most.

**Comment by robfig** [comment]
There is now different syntax -- `record()` vs `map()`
https://github.com/google/closure-templates/blob/master/documentation/reference/types.md

This ticket could probably be closed

**Comment by emspishak** [comment]
Correct, thanks @robfig!

The way to do this with maps now is:

```
    {let $formattableDays: map(
      'MONDAY':    'Monday',
      'TUESDAY':   'Tuesday',
      'WEDNESDAY': 'Wednesday',
      'THURSDAY':  'Thursday',
      'FRIDAY':    'Friday',
      'SATURDAY':  'Saturday',
      'SUNDAY':    'Sunday'
    ) /}

    {$formattableDays['MONDAY']} 
```
