### ISSUE TITLE
SoyToIncrementalDomSrcCompiler issue with self closing element tag

### ISSUE THREAD

**Issue by mairatma** [google/closure-templates#92]
If an element tag is self closed, the ending `/` is treated as an attribute, which causes errors since it's not a valid attribute name. For example:

```
{namespace Input}

{template .render}
  <input type="text" />
{/template}
```

This soy is compiled to:

```js
function $render(opt_data, opt_ignored, opt_ijData) {
  ie_open('input', null, null,
      'type', 'text',
      '/', '');
}
```

**Comment by sparhami** [comment]
I'm working on adding support for this. Initially, this will only be supported for void tags (e.g. `input` and `img`).

According to the spec, you can also have self-closing tags in SVG/MathML content (e.g. `<svg><path/></svg>`). All other self-closing tags are invalid HTML, though (all?) browsers treat them as just start tags rather than throwing a parse error. Since telling SVG content apart from non-svg content can be tricky (for example, could have a `<path />` in a standalone template), I'm going to just throw an error for all non-void self closing tags.

In the mean time, you should be able to do:

```
<input type="text">
```

instead.

**Comment by mairatma** [comment]
Yeah, not using self closing tags is no problem now that I know about this. I just wanted to let you know because the behavior was unexpected, hard to debug.
Thanks for taking a look at this :)

**Comment by mairatma** [comment]
@sparhami do you have any updates on this? There are more people using this now and asking me about it.

Also, it would be even better if you could just allow self closing tags for everything. Developers are very used to being able to do this, which makes using soy templates more complicated. Since browsers don't complain, there shouldn't be a problem, right?

**Comment by sparhami** [comment]
Self closing tags should now be supported for SVG content and void elements. Not sure if they have made it to the Github release yet. So you should be able to do:

```
<input>
<input />
<input></input>
```

SVG content has some support, but if the SVG content (e.g a `<circle>` tag) appears in a separate template, then the compiler will complain, since it can't be sure that it is SVG content (which does allow for self-closing tags).

The compiler will still complain about:

```
<span>
  <div />
  <div />
</span>
```

since in HTML, that is interpreted as:

```
<span>
  <div>
    <div>
    </div>
  </div>
</span>
```

Maintaining this behavior would require a runtime component to Incremental DOM that I don't think is really useful to have.

**Comment by mairatma** [comment]
Thanks, could you publish a version on [npm](https://www.npmjs.com/package/closure-templates-incrementaldom) with this and the other [issue](https://github.com/google/closure-templates/issues/96#issuecomment-237313394) you've commented on? That would be really helpful!
